<a href="https://colab.research.google.com/github/ksivaram2/Machine-Learning/blob/main/Lab_Task_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
##### 1.Create a vector (array) of 1XN dimension representing N- dimensional feature vector of a sample.
#### Write a program to compute the mean and variance of the elements present in the array.
import numpy as np

def compute_mean_and_variance(arr):
    mean = np.sum(arr) / len(arr)
    # Sample variance
    sample_variance = np.sum((arr - mean)**2) / (len(arr) - 1)
    # Population variance
    population_variance = np.sum((arr - mean)**2) / len(arr)
    return mean, sample_variance, population_variance

feature_vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

mean, sample_variance, population_variance = compute_mean_and_variance(feature_vector)

print("Feature Vector:", feature_vector)
print("Mean:", mean)
print("Sample Variance:", sample_variance)
print("Population Variance:", population_variance)

Feature Vector: [ 1  2  3  4  5  6  7  8  9 10]
Mean: 5.5
Sample Variance: 9.166666666666666
Population Variance: 8.25


In [6]:
### 2.Create two vectors each of dimension 1XM each representing N- dimensional feature vector of a sample.
### Write a program to compute the Covariance between them.
import numpy as np

# Function to compute the covariance between two 1xM dimensional feature vectors
def compute_covariance(X, Y):
    M = X.shape[1]
    mean_X = np.sum(X) / M
    mean_Y = np.sum(Y) / M
    covariance = np.sum((X - mean_X) * (Y - mean_Y)) / M
    return covariance

# Create two 1x10 dimensional feature vectors
X = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
Y = np.array([[11,12,13,14,15,16,17,18,19,20]])

# Compute the covariance between the two vectors
covariance = compute_covariance(X, Y)

print("Feature Vector X:", X)
print("Feature Vector Y:", Y)
print("Covariance between X and Y:", covariance)

Feature Vector X: [[ 1  2  3  4  5  6  7  8  9 10]]
Feature Vector Y: [[11 12 13 14 15 16 17 18 19 20]]
Covariance between X and Y: 8.25


In [7]:
### 3.Create two vectors each of dimension 1XN. Write a program to compute the Correlation between them.
import numpy as np

# Function to compute the correlation between two 1xN dimensional vectors
def compute_correlation(X, Y):
    mean_X = np.mean(X)
    mean_Y = np.mean(Y)
    covariance = np.sum((X - mean_X) * (Y - mean_Y))
    std_dev_X = np.sqrt(np.sum((X - mean_X)**2))
    std_dev_Y = np.sqrt(np.sum((Y - mean_Y)**2))
    correlation = covariance / (std_dev_X * std_dev_Y)
    return correlation

# Create two 1xN dimensional vectors
N = 10
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
Y = np.array([11,12,13,14,15,16,17,18,19,20])

# Compute the correlation between the two vectors
correlation = compute_correlation(X, Y)

print("Feature Vector X:", X)
print("Feature Vector Y:", Y)
print("Correlation between X and Y:", correlation)


Feature Vector X: [ 1  2  3  4  5  6  7  8  9 10]
Feature Vector Y: [11 12 13 14 15 16 17 18 19 20]
Correlation between X and Y: 1.0


In [8]:
### 4. Create a Matrix of MXN dimension representing the M-dimensional feature vector for N number of samples
###i. e (i,j)th entry of the matrix represents the ith feature of jth sample.
### Write a program to computethe covariance matrix and correlation matrix. Comment on takeaways from these matrixes.
import numpy as np

# Function to compute the covariance matrix and correlation matrix
def compute_covariance_and_correlation(matrix):
    # Compute the covariance matrix
    covariance_matrix = np.cov(matrix)

    # Compute the correlation matrix
    correlation_matrix = np.corrcoef(matrix)

    return covariance_matrix, correlation_matrix

# Create a matrix of MxN dimensions with the given feature vectors
matrix = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                   [11,12,13,14,15,16,17,18,19,20]])

# Compute the covariance matrix and correlation matrix
covariance_matrix, correlation_matrix = compute_covariance_and_correlation(matrix)

print("Feature Matrix:")
print(matrix)
print("\nCovariance Matrix:")
print(covariance_matrix)
print("\nCorrelation Matrix:")
print(correlation_matrix)

Feature Matrix:
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]

Covariance Matrix:
[[9.16666667 9.16666667]
 [9.16666667 9.16666667]]

Correlation Matrix:
[[1. 1.]
 [1. 1.]]
